# Generated by Django 3.2.7 on 2023-04-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100, verbose_name='Организация')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='User_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('login', models.EmailField(max_length=70, verbose_name='Логин')),
                ('passvord', models.CharField(max_length=50, verbose_name='Пароль')),
            ],
        ),
    ]
