# Generated by Django 3.2.7 on 2023-04-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_work_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=70, verbose_name='Фамилия')),
                ('organization', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Имя',
                'verbose_name_plural': 'Имена',
            },
        ),
        migrations.CreateModel(
            name='Work_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(auto_now_add=True, verbose_name='Время посещение')),
                ('end_time', models.DateField(auto_now_add=True, verbose_name='Время выхода')),
                ('created_ad', models.DateField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organizations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_work')),
            ],
        ),
        migrations.CreateModel(
            name='Organization_defaulr_wt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateField(auto_created=True, verbose_name='Время выхода')),
                ('start_time', models.DateField(auto_created=True, verbose_name='Время посешение')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organizations')),
            ],
        ),
    ]
